name: 'Azure App Service FTPS Deployment'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use Linux runner for FTPS compatibility

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install LFTP
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp  # Ensure LFTP is installed
  

      - name: Sync files to Azure App Service
        run: |
          $FTP_HOST: waws-prod-yt1-079.ftp.azurewebsites.windows.net
          $FTP_USER: azure-practice\$azure-practice  # Use your actual FTP username
          $FTP_PASS: 'JrwfoubgvipNNhG9TaA9LiPA8FRvSwmNxePnmakwSTunDjCQyMeo5BS82EpC'  # Store FTP password as GitHub Secret
          # Use lftp for FTPS deployment
          lftp -e "mirror -R ./ ./site/wwwroot; quit" -u $FTP_USER,$FTP_PASS ftps://$FTP_HOST

      - name: Verify Deployment
        run: |
          echo "Deployment completed. Verify files on Azure App Service."
