name: 'Azure App Service FTPS Deployment'

trigger:
  - main  # Trigger the pipeline on any push to the 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Use the Ubuntu image for the build agent

steps:
# Step 1: Install lftp for FTPS deployment
- script: |
    sudo apt-get install lftp -y
  displayName: 'Install lftp'

# Step 2: Deploy files to Azure Web App via FTPS
- script: |
    # Define FTPS credentials and server
    FTP_HOST="waws-prod-yt1-079.ftp.azurewebsites.windows.net"  # FTPS server URL
    FTP_USER="azure-practice\$azure-practice"  # FTPS Username (replace with actual username)
    FTP_PASS="JrwfoubgvipNNhG9TaA9LiPA8FRvSwmNxePnmakwSTunDjCQyMeo5BS82EpC"  # FTPS Password (replace with actual password)
    
    # Deploy content from './html' folder to the Azure Web App's wwwroot directory
    lftp -u "$FTP_USER","$FTP_PASS" "ftps://$FTP_HOST" -e "set ftp:passive-mode true; mirror -R ./html /site/wwwroot; bye"
  displayName: 'Deploy to Azure Web App via FTPS'

