name: 'Azure Web App Deployment'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use Linux runner for deployment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: 'Azure Web App Deploy'
        uses: Azure/webapps-deploy@v2
        with:
          app-name: 'azure-practice'  # Replace with your actual Azure Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Securely store the publish profile as a GitHub Secret
