name: 'App Service FTPS Deployment'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest  # Runs on Windows environment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Checkout the repository

      - name: Install FTP Client (lftp) and CA Certificates
        run: |
          choco install lftp  # Install the lftp FTP client
          # Manually install CA certificates from a trusted source
          Invoke-WebRequest -Uri "https://curl.se/ca/cacert.pem" -OutFile "$env:temp\cacert.pem"
          echo "CA certificates installed successfully."

      - name: FTPS Deploy to Azure App Service
        run: |
          # Define the FTPS server and credentials (hardcoded)
          $FTP_HOST="waws-prod-yt1-079.ftp.azurewebsites.windows.net"
          $FTP_USER="azure-practice\$azure-practice"  # Your FTPS Username
          $FTP_PASS="JrwfoubgvipNNhG9TaA9LiPA8FRvSwmNxePnmakwSTunDjCQyMeo5BS82EpC"  # Your FTPS Password
          $CACERT_PATH="$env:temp\cacert.pem"  # Path to the CA certificate

          # Deploy the HTML and CSS files directly from the root of the repository
          echo "Deploying to $FTP_HOST"

          # Upload files using lftp (upload everything in the root directory to /site/wwwroot)
          lftp -e "
          set ftp:ssl-force true
          set ssl:verify-certificate yes
          set ssl:ca-file $CACERT_PATH
          open ftps://$($FTP_USER):$($FTP_PASS)@$($FTP_HOST)
          mirror -R ./ /site/wwwroot --ignore-time --verbose
          bye
          "
