name: 'Azure App Service FTPS Deployment'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use Linux runner for LFTP compatibility

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install LFTP
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      - name: FTPS Deploy to Azure App Service
        run: |
          # Hardcoded FTPS credentials
          FTP_HOST="waws-prod-yt1-079.ftp.azurewebsites.windows.net"
          FTP_USER="azure-practice\$azure-practice"  # Replace with your actual FTP username
          FTP_PASS="JrwfoubgvipNNhG9TaA9LiPA8FRvSwmNxePnmakwSTunDjCQyMeo5BS82EpC"  # Replace with your actual FTP password
          # Upload the files to the 'site/wwwroot' directory on Azure App Service using FTPS
          lftp -u $FTP_USER,$FTP_PASS $FTP_HOST <<EOF
          mirror -R ./dist /site/wwwroot
          quit
          EOF
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}

      - name: Verify Deployment
        run: |
          echo "Deployment completed. Verify files on Azure App Service."
