name: 'Azure App Service FTPS Deployment'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use Linux runner for LFTP compatibility

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install LFTP
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      - name: FTPS Deploy to Azure App Service
        run: |
          # Hardcoded FTPS credentials
          FTP_HOST="waws-prod-yt1-079.ftp.azurewebsites.windows.net"
          FTP_USER="azure-practice\$azure-practice"
          FTP_PASS="JrwfoubgvipNNhG9TaA9LiPA8FRvSwmNxePnmakwSTunDjCQyMeo5BS82EpC"

          echo "Deploying to $FTP_HOST"

          # Upload files using LFTP
          lftp -e "
          set ftp:ssl-force true
          set ssl:verify-certificate no  # Disable SSL verification for testing
          open ftps://$FTP_USER:$FTP_PASS@$FTP_HOST
          mirror -R ./ /site/wwwroot --ignore-time --verbose
          bye
          "

      - name: Verify Deployment
        run: |
          echo "Deployment completed. Verify files on Azure App Service."
