name: 'Azure App Service FTPS Deployment'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use Linux runner for FTPS compatibility

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Sync files to Azure App Service
        uses: easymotion/ftp-action@v1
        with:
          server: waws-prod-yt1-079.ftp.azurewebsites.windows.net
          username: azure-practice\$azure-practice  # Use your actual FTP username
          password: 'JrwfoubgvipNNhG9TaA9LiPA8FRvSwmNxePnmakwSTunDjCQyMeo5BS82EpC'  # Store FTP password as GitHub Secret
          protocol: ftps  # FTPS protocol
          local-dir: ./  # Directory to upload from (root of your repository)
          remote-dir: /site/wwwroot  # Remote destination directory for Azure App Service

      - name: Verify Deployment
        run: |
          echo "Deployment completed. Verify files on Azure App Service."
